import localFont from "next/font/local";
import "./globals.css";
import TanstackQueryProvider from "@/components/partials/provider/TanstackQueryProvider";
import { Toaster } from "react-hot-toast";
import AuthForm from "@/components/templates/authForm";

import styles from "./layout.module.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});


const yekanBakh = localFont({
  src: [
    {
      path: "./fonts/Yekan_Bakh_Fanum_Semi_Bold.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-yekan",
  display: "swap",
});



const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className={yekanBakh.variable}>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}/
      >
        <TanstackQueryProvider>
          <header className={styles.head}>
            <Image
              src="/images/Torino1.png"
              alt="torino"
              width={150}
              height={50}
            />
            <div className={styles.middle}>
              <p>
                <Link href={"/"}>صفحه اصلی</Link>
              </p>
              <p>خدمات گردشگری</p>
              <p>درباره ما</p>
              <p>تماس با ما</p>
            </div>
            <AuthForm />
          </header>
          {children}
          <footer className={styles.footer}>
            <div className={styles.footertext}>
              <div>
                <h2>تورینو</h2>
                <p>درباره ما</p>
                <p>تماس با ما</p>
                <p>چرا تورینو</p>
                <p>بیمه مسافرتی</p>
              </div>
              <div>
                <h2>خدمات مشتریان</h2>
                <p>پشتیبانی آنلاین</p>
                <p>راهنمای خرید</p>
                <p>راهنمای استرداد</p>
                <p>پرسش و پاسخ</p>
              </div>
            </div>
            <div className={styles.footerleft}>
              <div className={styles.number}>
                <a className="mt-10">
                  <Image
                    src="/images/Torino1.png"
                    alt="تورینو"
                    width={150}
                    height={50}
                  />
                </a>
                <p className="mt-5">تلفن پشتیبانی:021-7584</p>
              </div>
              <div className={styles.pictures}>
                <Image
                  src="/images/state-airline-f45c55b21.png"
                  alt="سازمان هواپیمایی"
                  width={150}
                  height={50}
                />
                <Image
                  src="/images/passenger-rights-48368f811.png"
                  alt="حقوق مسافر"
                  width={150}
                  height={50}
                />
                <Image
                  src="/images/03ee625beaefc3d2c4a04b78ec2cf074ffceda78.jpg"
                  alt="بارکد"
                  width={150}
                  height={50}
                />

                <Image
                  src="/images/f71e9f370edf74cf16afe262d2695a18c2934c0c.png"
                  alt="نشان ملی"
                  width={150}
                  height={50}
                />
                <Image
                  src="/images/2a27bbd88c1ae3f08bb50c0d8ee89ae0da228702.png"
                  alt="نرخ بلیط"
                  width={150}
                  height={50}
                />
              </div>
            </div>
          </footer>
          <div className={styles.end}>
            <hr className="mx-auto w-[1200px] my-6"></hr>
            <p>کلیه حقوق این وب سایت متعلق به تورینو میباشد.</p>
          </div>
        </TanstackQueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
